[package]
authors = ["Alex Morales", "sfw.tools", "sfwtools.com"]
description = "Encode a string to base64."
edition = "2021"
license = "AGPL-3.0"
name = "base64"
version = "0.1.1"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
