[package]
authors = ["Alex Morales", "sfw.tools", "sfwtools.com"]
description = "Convert common physical units."
edition = "2021"
license = "AGPL-3.0"
name = "convert"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
abi = { path = "../abi" }
uom = { version = "0.38", default-features = false, features = ["f64", "si", "std"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
